trigger:
  branches:
    include:
    - main
resources:
  repositories:
  - repository: CapstoneRepo
    type: github
    endpoint: CapstoneDevOps-Repo-Connection
    name: Xoray11/CapstoneDevOps
variables:
- name: imageRepository
  value: 'healthchecks'
- name: containerRegistry
  value: 'acrcapstone3957.azurecr.io'
- name: dockerfilePath
  value: 'Dockerfile'
- name: tag
  value: 'latest'
- name: vmImageName
  value: 'ubuntu-latest'
stages:
- stage: __default
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: 6d15af64-176c-496d-b583-fd2ae21d4df4@1
      inputs:
        repository: CapstoneRepo
    - task: CmdLine@2
      displayName: 'Docker Login'
      inputs:
        script: |
          echo "$(acrPassword)" | docker login $(containerRegistry) -u acrcapstone3957 --password-stdin
    - task: CmdLine@2
      displayName: 'Create Empty Requirements Files'
      inputs:
        script: |
          touch requirements.txt requirements-dev.txt
    - task: CmdLine@2
      displayName: 'Docker Build'
      inputs:
        script: |
          docker build -t $(containerRegistry)/$(imageRepository):$(tag) -f $(dockerfilePath) .
    - task: CmdLine@2
      displayName: 'Docker Push'
      inputs:
        script: |-
          docker push $(containerRegistry)/$(imageRepository):$(tag)

