trigger:
  branches:
    include:
      - main
      - feature/k8s-deployment

variables:
  - group: keyvault-variable-group

stages:
  # ==================================
  # BUILD IMAGE ON AGENT & PUSH TO ACR
  # ==================================
  - stage: Build
    displayName: Build and Push Image
    jobs:
      - job: BuildImage
        displayName: Docker Build & Push
        pool:
          vmImage: ubuntu-latest
        steps:
          # Bypasses the student subscription block by compiling locally on the agent
          - task: Docker@2
            displayName: Build and Push to ACR
            inputs:
              containerRegistry: 'ACR-Connection'
              repository: 'healthchecks'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              buildContext: '$(Build.SourcesDirectory)'
              tags: |
                $(Build.BuildId)
                latest

  # ======================
  # DEPLOY TO AKS
  # ======================
  - stage: Deploy
    displayName: Deploy application to AKS
    dependsOn: Build
    jobs:
      - job: Deploy
        pool:
          vmImage: ubuntu-latest
        steps:
          # Create / Update Kubernetes Secret from Key Vault
          - task: Kubernetes@1
            displayName: Create Kubernetes Secret from Key Vault
            inputs:
              connectionType: Azure Resource Manager
              azureSubscription: azure-connection-capstone
              azureResourceGroup: rg-capstone-project
              kubernetesCluster: shopping-aks
              command: createSecret
              arguments: >
                generic app-secret
                --from-literal=SECRET_KEY=$(django-secret-key)
                --dry-run=client -o yaml | kubectl apply -f -

          # Injects your ACR connection details into AKS so it can pull the image
          - task: Kubernetes@1
            displayName: Create ACR Pull Secret in AKS
            inputs:
              connectionType: Azure Resource Manager
              azureSubscription: azure-connection-capstone
              azureResourceGroup: rg-capstone-project
              kubernetesCluster: shopping-aks
              command: createSecret
              secretType: dockerRegistry
              secretName: acr-pull-secret
              dockerRegistryEndpoint: 'ACR-Connection'

          # Apply Kubernetes Deployment
          - task: Kubernetes@1
            displayName: Deploy application to AKS
            inputs:
              connectionType: Azure Resource Manager
              azureSubscription: azure-connection-capstone
              azureResourceGroup: rg-capstone-project
              kubernetesCluster: shopping-aks
              command: apply
              useConfigurationFile: true
              configuration: kubernetes/deployment.yaml