apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthchecks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthchecks
  template:
    metadata:
      labels:
        app: healthchecks
    spec:
      containers:
        - name: healthchecks
          image: acrcapstone1769.azurecr.io/healthchecks:latest
          command: ["/bin/sh"]
          args:
            - -c
            - |
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000
          ports:
            - containerPort: 8000
          env:
            - name: ALLOWED_HOSTS
              value: "*"